name: build 11ty site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Build TinaCMS
        env:
          TINA_PUBLIC_CLIENT_ID: '1421083b-6294-4036-8c10-388b460bb401'
          TINA_TOKEN: 'f0ac9b3b8a83a26cf68fd79c13603c0ffb2ab623'
        run: |
          npm ci
          npx tinacms build
      - name: Install dependencies & build
        run: |
          npm install
          npm run build-gp
      - uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
